### ISSUE TITLE
gulp check-deploy 报错  

### ISSUE THREAD

**Issue by wwb568109135** [angular/angular-cn#22]
Ubuntu 环境下

wwb@ubuntu:~/gitlearnDemo/angular-cn$ gulp check-deploy
(node:9510) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[18:18:25] Using gulpfile ~/gitlearnDemo/angular-cn/gulpfile.js
[18:18:25] Starting '_shred-clean-devguide'...
[18:18:25] Starting '_copy-example-boilerplate'...
[18:18:25] Copying example boilerplate files
[18:18:25] Starting '_shred-clean-devguide-shared-jade'...
[18:18:25] Starting '_shred-clean-api'...
[18:18:25] Starting 'build-dart-cheatsheet'...
[18:18:26] { Error: ENOENT: no such file or directory, open '../angular/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at packageInfo (/home/wwb/gitlearnDemo/angular-cn/tools/api-builder/angular.io-package/services/packageInfo.js:13:24)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:75:15)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:119:18
    at Array.forEach (native)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:118:25
    at Array.forEach (native)
    at Dgeni.configureInjector (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:117:14)
    at Dgeni.generate (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:149:8)
    at buildApiDocs (/home/wwb/gitlearnDemo/angular-cn/gulpfile.js:1048:18)
    at Gulp.<anonymous> (/home/wwb/gitlearnDemo/angular-cn/gulpfile.js:518:10)
    at module.exports (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../angular/package.json' }
[18:18:26] Error: ENOENT: no such file or directory, open '../angular/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at packageInfo (/home/wwb/gitlearnDemo/angular-cn/tools/api-builder/angular.io-package/services/packageInfo.js:13:24)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:75:15)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:119:18
    at Array.forEach (native)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:118:25
    at Array.forEach (native)
    at Dgeni.configureInjector (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:117:14)
    at Dgeni.generate (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:149:8)
    at buildApiDocs (/home/wwb/gitlearnDemo/angular-cn/gulpfile.js:1048:18)
    at Gulp.<anonymous> (/home/wwb/gitlearnDemo/angular-cn/gulpfile.js:518:10)
    at module.exports (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
[18:18:26] 'build-dart-cheatsheet' errored after 397 ms
[18:18:26] Error: ENOENT: no such file or directory, open '../angular/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at packageInfo (/home/wwb/gitlearnDemo/angular-cn/tools/api-builder/angular.io-package/services/packageInfo.js:13:24)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:75:15)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at get (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:48:43)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at invoke (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/node_modules/di/lib/injector.js:70:31)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:119:18
    at Array.forEach (native)
    at /home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:118:25
    at Array.forEach (native)
    at Dgeni.configureInjector (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:117:14)
    at Dgeni.generate (/home/wwb/gitlearnDemo/angular-cn/node_modules/dgeni/lib/Dgeni.js:149:8)
    at buildApiDocs (/home/wwb/gitlearnDemo/angular-cn/gulpfile.js:1048:18)
    at Gulp.<anonymous> (/home/wwb/gitlearnDemo/angular-cn/gulpfile.js:518:10)
    at module.exports (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/wwb/gitlearnDemo/angular-cn/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:159:18)
    at node.js:444:3
[18:18:26] Finished '_shred-clean-devguide-shared-jade' after 678 ms
[18:18:26] Finished '_shred-clean-devguide' after 1.03 s
[18:18:26] Finished '_shred-clean-api' after 465 ms
[18:18:26] Finished '_copy-example-boilerplate' after 1.64 s
wwb@ubuntu:~/gitlearnDemo/angular-cn$ gulp check-deploy

**Comment by asnowwolf** [comment]
你需要在angular-cn的同级目录下下载一份angular库的源码，因为要根据它来编译出API文档。我已经把这个步骤补充到了README.md中。
