### ISSUE TITLE
本地预览出错

### ISSUE THREAD

**Issue by wyplovezss** [angular/angular-cn#229]
D:\Users\wyplovezss\Documents\Nodejs\angular-cn\gulpfile.js:119
    fullSiteBuildTasks.some((task) => argv['_'].indexOf(task) >= 0);
                                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\wyplo\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\wyplo\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)
    at module.exports (C:\Users\wyplo\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)

**Comment by asnowwolf** [comment]
确保你的NodeJS是6.9以上，因为是文档站，所以没有做向下兼容。
