### ISSUE TITLE
使用Linux环境进行compile报错

### ISSUE THREAD

**Issue by njustyangkai** [angular/angular-cn#230]
我使用CentOs和Ubuntu进行compile到最后都会在执行“harp compile .www”报错，帮看下谢谢！

[10:22:31] npm ERR! Please include the following file with any support request:
npm ERR!     /angular/angular-cn/npm-debug.log

[10:22:31] completed: npm run harp -- compile . www
[10:22:31] NODE_ENV: production
[10:22:31] renameIfExistsSync cannot rename, path not found: public/docs/dart/latest/_api-tmp-hide-from-jade
[10:22:31] jade2ng: false
[10:22:31] 'build-compile' errored after 1.08 min
[10:22:31] Error: 1
    at formatError (/node/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/node/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/angular/angular-cn/node_modules/orchestrator/index.js:264:8)
    at /angular/angular-cn/node_modules/orchestrator/index.js:275:23
    at finish (/angular/angular-cn/node_modules/orchestrator/lib/runTask.js:21:8)
    at /angular/angular-cn/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/angular/angular-cn/node_modules/q/q.js:864:24)
    at /angular/angular-cn/node_modules/q/q.js:890:30
    at Promise.when (/angular/angular-cn/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/angular/angular-cn/node_modules/q/q.js:808:41)
    at /angular/angular-cn/node_modules/q/q.js:624:44
    at runSingle (/angular/angular-cn/node_modules/q/q.js:137:13)
    at flush (/angular/angular-cn/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

**Comment by njustyangkai** [comment]
使用Mac OS 也出现了同样的错误。。。求解答！

**Comment by asnowwolf** [comment]
如果你们不用dart版的话就用`gulp build-compile --lang="(ts|js)"`编译吧，我也没做过dart版的编译环境。

**Comment by asnowwolf** [comment]
可使用 https://github.com/ng-nice/angular.cn-prebuilt 的预编译版本。
