### ISSUE TITLE
无法编译提示primordials没有定义

### ISSUE THREAD

**Issue by wyplovezss** [angular/angular-cn#404]
D:\angular-cn-aio>gulp build-compile --lang="(ts|js)"
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (D:\angular-cn-aio\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\angular-cn-aio\node_modules\natives\index.js:
55:10)
    at Object.<anonymous> (D:\angular-cn-aio\node_modules\vinyl-fs\node_modules\
graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by asnowwolf** [comment]
现在的构建脚本已经不是这样的了。最新版在 aio 分支下。另外，如果你只是想用成品网站，可以不必自己编译，直接把 https://github.com/ng-docs/ng-docs.github.io clone 下来，然后编写一个 try_files 规则部署起来就可以了。

**Comment by wyplovezss** [comment]
搞定，感谢指点！发自我的华为手机
