### ISSUE TITLE
运行gulp check-deploy命令进行编译时出现报错

### ISSUE THREAD

**Issue by heboliufengjie** [angular/angular-cn#46]
$ gulp check-deploy
D:\test\angular-cn\gulpfile.js:514
      spawnInfo = spawnExt('npm', ['install', ...sources], {cwd: EXAMPLES_PATH});
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\g                ulp\3.9.1\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\lifto                ff\2.2.4\liftoff\index.js:193:16)
    at module.exports (C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\flagged-re                spawn\0.3.2\flagged-respawn\index.js:17:3)

$ gulp check-deploy
[17:26:34] Building docs for: ts|js|dart
D:\test\angular-cn\gulpfile.js:1443
  throw new Error('API related tasks require the angular2 repo to be at ' + ngPath);
  ^

Error: API related tasks require the angular2 repo to be at D:/test/angular-dart
    at checkAngularProjectPath (D:\test\angular-cn\gulpfile.js:1443:9)
    at configLangs (D:\test\angular-cn\gulpfile.js:131:5)
    at Object.<anonymous> (D:\test\angular-cn\gulpfile.js:134:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\g                ulp\3.9.1\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\lifto                ff\2.2.4\liftoff\index.js:193:16)
    at module.exports (C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\flagged-re                spawn\0.3.2\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\lifto                ff\2.2.4\liftoff\index.js:185:9)
    at C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\liftoff\2.2.4\liftoff\inde                x.js:159:9
    at C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\v8flags\2.0.11\v8flags\ind                ex.js:108:14
    at C:\Users\fengjie.liu\AppData\Roaming\npm\node_modules\.gulp_npminstall\v8flags\2.0.11\v8flags\ind                ex.js:36:12

不知道是不是修bug 时带上去的

**Comment by asnowwolf** [comment]
这是缺少dart环境导致的问题。不过现在我也只是编译ts和js版，dart版本从上个月官方调整了构建脚本之后我也没试验通过。你可以为命令行加上“--lang="(ts|js)"”选项来暂时跳过dart编译
